name: synergy_dms_app
description: "Synergy University Document Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.4.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  intl: ^0.19.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
